title: Shadows in Paradise
# description: My very nice blog
author: "Toshiki Hinai"

theme: minima

# base_url: /gh-pages-minima-starter

# Minima social links
# twitter_username: xurxosanz
github_username: CATSEyebrow
linkedin_username: toshiki-hinai
rss: rss

# Minima: show excerpts in the frontpage
show_excerpts: false

minima:
  skin: dark
  date_format: "%Y-%m-%d"

## Minima: custom header links
header_pages:
#  - _pages/frontpage.md
  - _pages/about.md
#  - _pages/archive.md

include:
    - _pages

exclude: 
    - .gitignore
    - docker-compose.yml
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
